<?php 
/**
 * Implements hook_menu()
 */
function my_database_menu() {
  $items = array();
  $items['db_insert'] = array(
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('my_database_form'),
    'access callback' => TRUE
  );
  $items['db_select'] = array(
    'title'           => 'Select',
    'page callback'   => 'select_table',
    'access callback' => TRUE
  );
  $items['db_update/%'] = array(
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('my_database_form'),
    'access callback' => TRUE
  );
  $items['db_delete/%'] = array(
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('delete_form'),
    'access callback' => TRUE
  );

  return $items;
}
/**
 * Create and edit data form
 */
function my_database_form($form, &$form_state) {
  if (arg(0) == 'db_update' && !empty(arg(1))){
    $db_s = db_select('custom_table','n')
    ->fields('n')
    ->condition ('id', arg(1))
    ->execute()
    ->fetchAssoc();
  }

  $form['number'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Number'),
    '#required'      => TRUE,
     '#default_value'=> isset($db_s['number']) ? $db_s['number'] : ''
  );
  $form['teaser'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Teaser'),
    '#required'      => TRUE,
    '#default_value' => isset($db_s['teaser']) ? $db_s['teaser'] : ''
  );
  $form['text'] = array(
    '#type'          => 'textarea',
    '#title'         => t('Text'),
    '#required'      => TRUE,
    '#default_value' => isset($db_s['text']) ? $db_s['text'] : ''
  );
  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => (arg(1) ? t('Update data') : t('Insert data')),
  );

  return $form;
}

/**
 * Delete data form
 */ 
function delete_form($form, &$form_state) {
  $form['delete'] = array(
    '#type'   => 'submit',
    '#value'  => t('Delete data'),
    '#submit' => array('delete_form_button')
  );
  $form['back'] = array(
    '#type'   => 'submit',
    '#value'  => t('Back'),
    '#submit' => array('back_button')
  );

  return $form;
}

/**
 * Validate function for my_form. 
 */ 
function my_database_form_validate($form, &$form_state) { 

  if (!is_numeric($form_state['values']['number'])) {
    form_set_error('number',t('Value in field "Number" is wrong.'));
  }
}

/**
 * Submit function for back.
 */
function back_button($form, &$form_state) {
  $form_state['redirect'] = 'db_select';
}
/**
 * Submit function for delete.
 */
function delete_form_button($form, &$form_state) {
  if (arg(1)) {
  db_delete('custom_table')
    ->condition ('id', arg(1))
    ->execute();
    $form_state['redirect'] = 'db_select';
    drupal_set_message(t('Delete data from "custon_table" complite'));
  }
}


/**
 * Submit function for my_form.
 */
function my_database_form_submit($form, &$form_state) {
  if (arg(1)) {
  db_update('custom_table')
    ->fields(array(
      'number' => $form_state['values']['number'],
      'teaser' => $form_state['values']['teaser'],
      'text'   => $form_state['values']['text'],
    ))
    ->condition ('id', arg(1))
    ->execute();
    drupal_set_message(t('Update data from "custon_table" complite'));
  }
  else {
    db_insert('custom_table')
    ->fields(array(
      'number' => $form_state['values']['number'],
      'teaser' => $form_state['values']['teaser'],
      'text'   => $form_state['values']['text'],
    ))
    ->execute();
    drupal_set_message(t('Insert data from "custon_table" complite'));
  }
  $form_state['redirect'] = 'db_select';
}

/**
 * Callback function select_data
 */
function select_table() {
  $db_s = db_select('custom_table','n')
  ->fields('n')
  ->orderBy('id','ASC')
  ->execute()
  ->fetchAll();
  $header = array(t('id'), t('number'), t('teaser'), t('text') , t('action'));

  if (empty($db_s)) {
    return t('"custon_table" is empty!');
  }
  else{
    foreach ($db_s as $value) {
      $rows[] = array(
        $value->id,
        $value->number,
        $value->teaser,
        $value->text,
        l(t('Edit'), 'db_update/'.$value -> id).' / '. l(t('Delete'), 'db_delete/'.$value -> id),
      );
    }
    return theme('table', array('header' => $header, 'rows' => $rows));
  }
}