<?php 
/**
 * Implements hook_block_info()
 */
function block_view_block_info(){
	$info = array();
	$info['my_block'] = array(
		'info' => 'My block',
	);
	return $info;
}
/**
 * Implements hook_block_view()
 */
function block_view_block_view($mash_name = ''){
	$block = array();
	if ($mash_name == 'my_block' && user_access('access block_view')) {
		$block['subject'] = 'Block Title';
		$block['content'] = '<b>Block</b> content...';
	}
	elseif ($mash_name == 'my_block') {
		$block['subject'] = 'Block Title';
		$block['content'] = '<b>Access to view this content is denied.</b>';
	}
	return $block;
}
/**
 * Implements hook_permission()
 */
function block_view_permission(){
	$access = array();
	$access['access block_view'] = array(
		'title'       => 'Access my Block',
		'description' => 'access to view this content is denied.'
	);
	return $access;
}