<?php 
/**
 * Implements hook_block_info()
 */
function block_view_block_info() {
  $info = array();
  $info['my_block'] = array(
    'info' => t('My block'),
  );

  return $info;
}

/**
 * Implements hook_block_view().
 */
function block_view_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'my_block':
      if (user_access('access block_view')) {
        $block['subject'] = t('Block Title');
        $block['content'] = t('Block content...');
      }
      else {
        $block['subject'] = t('Block Title');
        $block['content'] = t('Access to view this content is denied.');
      };
    }

  return $block;
}

/**
 * Implements hook_permission()
 */
function block_view_permission() {
  $access = array();
  $access['access block_view'] = array(
    'title'       => t('Access my Block'),
    'description' => t('description Access my Block')
  );

  return $access;
}