<?php 
/**
 * Implements hook_menu()
 */
function my_theming_menu() {
  $items = array();
  $items['my-theming'] = array(
    'title'           => 'My Theming',
    'page callback'   => 'my_theming',
    'access callback' => TRUE
  );

  return $items;
}

/**
 * Callback function
 */
function my_theming() {

  return my_theming_list() . my_theming_table() . my_theming_fieldset() . my_theming_image_style() . my_theming_html_page();
}

/**
 * Callback function my_theming_list
 */
function my_theming_list() {
  $variables = array(
    'items'      => array(),
    'title'      => t('My list items'),
    'type'       => 'ol',
    'attributes' => array(),
  );
  $variables['items'][] = 'one';
  $variables['items'][] = 'two';
  $variables['items'][] = array(
    'data' => 'three',
    'children' => array('one','two', array(
      'data' => 'three',
      'children' => array('one','two', array(
          'data' => 'three',
          'children' => array('one','two', 'three'),
          )
        )
      )
    )
  );

  return theme('item_list', $variables);
}

/**
 * Callback function my_theming_table
 */
function my_theming_table() {
  $items = array(
    array(
      'sender'   => 'Lorem',
      'receiver' => 'Dolorem',
      'message'  => 'This is a message',
      'amount'   => 5,
    ),
    array(
      'sender'   => 'Dolorem',
      'receiver' => 'Lorem',
      'message'  => 'This is the reply',
      'amount'   => 7,
    ),
  );
  $header = array(t('From'), t('To'), t('Message'), t('Amount'));
  $rows = array();

  foreach($items as $item) {
    $rows[] = array(
      $item['sender'],
      $item['receiver'],
      $item['message'],
      $item['amount'],
    );
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * Callback function my_theming_fieldset
 */
function my_theming_fieldset() {
  drupal_add_library('system', 'drupal.collapse');
  $element = array( 
    '#title'       => t('Fieldset'),
    '#children'    => t('This is main text in fieldset!'), 
    '#collapsible' => TRUE, 
    '#collapsed'   => TRUE,
    '#attributes'  => array(
      'class' => array(
        'collapsible', 
        'collapsed'
      )
    ), 
  ); 

  return theme('fieldset', array('element' => $element));
}

/**
 * Callback function my_theming_image_style
 */
function my_theming_image_style() {
  $img = array(
    'path'       => 'Ant-man.jpg',
    'style_name' => 'large',
    'alt'        => t('Alternate Text'),
    'title'      => t('Title Text'),
  );

  return theme('image_style', $img);
}

/**
 * Implements hook_theme()
 */
function my_theming_theme($existing, $type, $theme, $path) {
  $theme = array(
    'my_theming_template' => array(
      'variables' => array(
        'text_one' => NULL, 
        'text_two' => NULL
      ),
      'template' => 'my_page'
    ),
    'my_theming_function' => array(
      'variables' => array(
        'text_one' => NULL,
        'text_two' => NULL
      ),
    ),
  );

  return $theme;
}

/**
 * Callback function usinf HTML output.
 */
function my_theming_html_page() {
  $text_one = "This is text one";
  $text_two = "This is text two";

  return theme('my_theming_template', array('text_one' => $text_one, 'text_two' => $text_two));
}

/**
 *Theme function
 */
function theme_my_theming_function($variables) {
  $output  = "<h1>" . $variables['text_one'] . "</h1>";
  $output .= "<strong>" . $variables['text_two'] . "<strong>";

  return $output;
}