<?php
/**
 * Implements hook_menu()
 */
function my_forms_menu() {
  $items = array();
  $items['my-forms'] = array(
    'title'          => 'Contacts',
    'page callback'  => 'drupal_get_form',
    'page arguments' => array('my_forms_form'),
    'access callback'=> TRUE);

  return $items;
}

/**
 * Callback function
 */
function my_forms_form($form, &$form_state) {
  $form['f_name'] = array(
    '#type'      => 'textfield',
    '#title'     => t('First name'),
    '#maxlength' => 127,
  );
  $form['l_name'] = array(
    '#type'      => 'textfield',
    '#title'     => t('Last name'),
    '#maxlength' => 127,
  );
  $form['n_name'] = array(
    '#type'      => 'textfield',
    '#title'     => t('Nick name'),
    '#maxlength' => 20,
    '#required'  => TRUE,
  );
  $form['email'] = array(
    '#type'      => 'textfield',
    '#title'     => t('E-Mail'),
    '#maxlength' => 20,
    '#required'  => TRUE,
  );
  $form['phone'] = array(
    '#type'      => 'textfield',
    '#title'     => t('Phone'),
    '#maxlength' => 10,
  ); 
  $form['sex'] = array(
    '#title'      => t('Your sex'),
    '#type'       => 'radios',
    '#options'    => array('male' => t('Male'),'famele' => t('Famele'))
  );
  $form['selectbox'] = array(
    '#type'    => 'select',
    '#title'   => t('Country'),
    '#options' => array(
      1 => t('Ukraine'),
      2 => t('Russia'),
      3 => t('USA'),
    ),
    '#description' => t('Choose an option.'),
  );
  $form['msg'] = array(
    '#type'     => 'textarea',
    '#title'    => t('Messaging'),
    '#required' => TRUE,
  );
  $form['checkbox'] = array(
    '#type'      => 'checkbox',
    '#title'     => t('Accept'),
    '#required'  => TRUE,
  );
  $form['contact'] = array(
    '#type'        => 'fieldset', 
    '#title'       => t('Fieldset'), 
    '#collapsible' => TRUE, 
    '#collapsed'   => FALSE,
    '#value'       => t('Send form'),
  );
  $form['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Send form'),
  );

  return $form;
}

/**
 * Validate function for my_form. 
 */ 
function my_forms_form_validate($form, &$form_state) { 
  if (!is_numeric($form_state['values']['phone'])) {
    form_set_error('phone', t('Value in field "Phone" is wrong.'));
    if (valid_email_address($form_state['values']['email']) == FALSE){
      form_set_error('email', t('Value in field "Email" is wrong.'));
    }
  }
}

/**
 * Submit function for  my_form.
 */
function my_forms_form_submit($form, &$form_state) {
  drupal_set_message(
    t('You First name: ')   . $form_state['values']['f_name']    .'<br>'.
    t('You Last name: ')    . $form_state['values']['l_name']    .'<br>'.
    t('You Nick name: ')    . $form_state['values']['n_name']    .'<br>'.
    t('You Email: ')        . $form_state['values']['email']     .'<br>'.
    t('You Phone number:')  . $form_state['values']['phone']     .'<br>'.
    t('You sex: ')          . $form_state['values']['sex']       .'<br>'.
    t('You country: ')      . $form_state['values']['selectbox'] .'<br>'.
    t('You Message: ')      . $form_state['values']['msg']       .'<br>'
  );
}